# Generated by Django 3.1.7 on 2021-03-11 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='назание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('creation_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='дата создания фильма')),
                ('pg_raiting', models.CharField(choices=[('G', 'без ограничений'), ('PG', 'детям рекомендуется смотреть фильм с родителями'), ('PG-13', 'просмотр не желателен детям до 13 лет'), ('R', 'лица, не достигшие 17-летнего возраста, только в сопровождении родителей'), ('NC-17', 'лица 17-летнего возраста и младше не допускаются')], default=None, max_length=20, null=True, verbose_name='тип')),
                ('file_path', models.FileField(blank=True, upload_to='film_works/', verbose_name='файл')),
                ('rating', models.FloatField(blank=True, db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='рейтинг')),
                ('type', models.CharField(choices=[('movie', 'фильм'), ('tv_show', 'шоу')], default=None, max_length=20, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'кинопроизведение',
                'verbose_name_plural': 'кинопроизведения',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описнаие')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('surname', models.CharField(default='', max_length=255, verbose_name='фамилия')),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
            },
        ),
        migrations.CreateModel(
            name='MoviesPersons',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('actor', 'актер'), ('writer', 'сценарист'), ('director', 'рижесер')], max_length=20, verbose_name='тип занятости')),
                ('filmwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_admin.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_admin.person')),
            ],
            options={
                'unique_together': {('filmwork', 'person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='MoviesGenres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filmwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_admin.filmwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_admin.genre')),
            ],
            options={
                'unique_together': {('filmwork', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(through='movies_admin.MoviesGenres', to='movies_admin.Genre'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='in_films', related_query_name='film', through='movies_admin.MoviesPersons', to='movies_admin.Person'),
        ),
    ]
